### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by Tot7uafag** [viniciusgf2/Ambience#93]
custom music and all the other sound ingame stops when console shows this:

[21:19:03] [Ambience Player Thread/INFO] [STDERR]: [vazkii.ambience.PlayerThread:run:74]: java.lang.NullPointerException
[21:19:03] [Ambience Player Thread/INFO] [STDERR]: [vazkii.ambience.PlayerThread:run:74]: 	at vazkii.ambience.PlayerThread.next(PlayerThread.java:82)
[21:19:03] [Ambience Player Thread/INFO] [STDERR]: [vazkii.ambience.PlayerThread:run:74]: 	at vazkii.ambience.PlayerThread.run(PlayerThread.java:71)

Is there something i can do about it?

**Comment by Tot7uafag** [comment]
solved
